<div>
    <span style="color: #0000CC;">Note: Field content must less than 73 character</span>
    <fieldset>
        <div class="form-group">
            <label for="fontname" class="col-lg-2 control-label">Font</label>    
            <div class="col-lg-10">
                <select class="form-control" id="fontname" name="fontname">
                    <option value="Arial">Arial</option>
                    <option value="Ryumin">Ryumin</option>
                    <option value="Gothic">Gothic</option>
                    <option value="Midashi">Midashi</option>
                    <option value="Futo">Futo</option>
                </select>
            </div>
        </div>
        <input type="hidden" id="filename" name="filename" value="<?= $this->filename; ?>">
        <?php foreach ($this->fieldList as $field) { ?>
            <?php if ('Text' == $field['FieldType']) { ?>
                <div class="form-group">
                    <label for="<?= $field['FieldName'] ?>" class="col-lg-2 control-label"><?= $field['FieldName'] ?></label>
                    <div class="col-lg-10">
                        <input type="text" class="form-control" id="<?= $field['FieldName'] ?>" name="<?= $field['FieldName'] ?>" value="<?= isset($field['FieldValue']) ? $field['FieldValue'] : '' ?>">
                    </div>

                </div>
            <?php } ?>
        <?php } ?>
    </fieldset>
</div>