<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sPdf Demo%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('This application use for demo about pdf feature. User can chooise the template, add text and download pdf file according by template'), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?></p>
</div>

<div class="col-lg-6s">
    <div class="well bs-component">
        <?php $form->prepare(); // The correct enctype is set here ?>
        <?php echo $this->form()->openTag($form); ?>
        
        <?php echo $this->formFileSessionProgress();?>
        
        <div class="form-element">
            <?php $fileElement = $form->get('pdf-file'); ?>
            <?php echo $this->formLabel($fileElement); ?>
            <?php echo $this->formFile($fileElement); ?>
            <?php echo $this->formElementErrors($fileElement); ?>
        </div>

        <button>Submit</button>

        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>


<!-- Twitter Bootstrap progress bar styles:
     http://twitter.github.com/bootstrap/components.html#progress -->
<div id="progress" class="help-block">
    <div class="progress progress-info progress-striped">
        <div class="bar"></div>
    </div>
    <p></p>
</div>

<div class="jumbotron">
    <form name="change-text-form" id="change-text-form" action="/change-text">
        <input type="text" name="inp-title" id="inp-title">
        <button>Change Title</button>
    </form>
</div>

<div class="jumbotron" id="image_container">
</div>

<script src="/js/jquery.min.js"></script>
<script src="/js/jquery.form.js"></script>
<script>
    var progressInterval;
    
    function getProgress(){
        var url = '/upload-progress?id=' +$('#progress_key').val();
        $.getJSON(url, function (data){
           if (data.status && !data.status.done){
               var value = Math.floor((data.status.current / data.status.total) * 100);
               showPrgress(value, 'Uploading...');
           } else {
               showProgress(100, 'Completed!');
               clearInterval(progressInterval);
           }
        });
    }
    
    function startProgress(){
        showProgress(0, 'Starting upload...');
        progressInterval = setInterval(getProgress, 900);
    }
    
    function showProgress(amount, message){
        $('#progress').show();
        $('#progress .bar').width(amount + '%');
        $('#progress > p').html(message);
        if (amount < 100){
            $('#progress .progress')
                .addClass('progress-info active')
                .removeClass('progress-success');
        } else {
            $('#progress .progress')
                .removeClass('progress-info active')
                .addClass('progress-success');
        }
    }
    
    $(function (){
        $('#change-text-form').on('submit', function (e){
            e.preventDefault();
            
            $(this).ajaxSubmit({
                beforeSubmit: function(arr, $from, options){
                    arr.push({name: 'isAjax', value:"1"});
                },
                success:function(response, statusText, xhr, $form){

                    if (response.status){
                        imageUrl = '/img/pdfThumb.jpg?timestamp=' + new Date().getTime();
                        $("#image_container").html("<img src='" + imageUrl + "'>");
                    } else {
                    }            
                },
                error:function(a, b, c){
                    console.log(a,b,c);
                }
            });            
        }); 
        
        $('#upload-form').on('submit', function (e){
            e.preventDefault();
            
            if($('#pdf-file').val() == ''){
                return;
            }
            
            $(this).ajaxSubmit({
                beforeSubmit: function(arr, $from, options){
                    arr.push({name: 'isAjax', value:"1"});
                },
                success:function(response, statusText, xhr, $form){
                    clearInterval(progressInterval);
                    showProgress(100, 'Completed!');

                    if (response.status){
                        imageUrl = '/img/pdfThumb.jpg?timestamp=' + new Date().getTime();
                        $("#image_container").html("<img src='" + imageUrl + "'>");
                    } else {
                        var fileInput = $('#pdf-file');
                        fileInput.replaceWith(fileInput.val('').clone(true));
                    }            
                },
                error:function(a, b, c){
                    console.log(a,b,c);
                }
            });            
             // Start the progress polling
            startProgress();
        });        
    });
</script>